// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Plugin Manifest Schema per ADR-0010
 */
export type PluginManifest = { plugin_id: string, name: string, version: string, author: string, requested_capabilities: Array<string>, };
