use crate::model_errors::ModelError;
use crate::provider::ModelProvider;
use sidra_domain::{CompletionRequest, CompletionResponse, TokenUsage, ToolCall};
use ulid::Ulid;

pub struct AnthropicProvider {
    pub api_key: String,
}

impl AnthropicProvider {
    pub fn new(api_key: impl Into<String>) -> Self {
        Self {
            api_key: api_key.into(),
        }
    }
}

impl ModelProvider for AnthropicProvider {
    fn name(&self) -> &'static str {
        "anthropic"
    }

    fn complete(&self, request: &CompletionRequest) -> Result<CompletionResponse, ModelError> {
        if self.api_key.is_empty() {
            return Err(ModelError::ProviderUnavailable {
                provider: self.name().to_string(),
                reason: "API key is missing".to_string(),
            });
        }

        let tool_calls = request
            .tools
            .first()
            .map(|t| vec![ToolCall {
                id: format!("toolu_{}", Ulid::new()),
                name: t.name.clone(),
                arguments_json: r#"{"status":"processed"}"#.to_string(),
            }])
            .unwrap_or_default();

        let prompt_tokens = request.messages.iter().map(|m| m.content.len() / 4).sum();
        let completion_tokens = 20;

        Ok(CompletionResponse {
            id: format!("msg_{}", Ulid::new()),
            content: "Response generated by Anthropic Claude adaptor".to_string(),
            tool_calls,
            usage: TokenUsage {
                prompt_tokens,
                completion_tokens,
                total_tokens: prompt_tokens + completion_tokens,
                estimated_cost_usd: (prompt_tokens as f64 * 0.000003) + (completion_tokens as f64 * 0.000015),
            },
            provider_name: self.name().to_string(),
        })
    }
}
