use crate::model_errors::ModelError;
use crate::provider::ModelProvider;
use sidra_domain::{CompletionRequest, CompletionResponse, TokenUsage, ToolCall};
use ulid::Ulid;

pub struct OllamaProvider {
    pub endpoint: String,
}

impl OllamaProvider {
    pub fn new(endpoint: impl Into<String>) -> Self {
        Self {
            endpoint: endpoint.into(),
        }
    }
}

impl Default for OllamaProvider {
    fn default() -> Self {
        Self::new("http://localhost:11434")
    }
}

impl ModelProvider for OllamaProvider {
    fn name(&self) -> &'static str {
        "ollama"
    }

    fn complete(&self, request: &CompletionRequest) -> Result<CompletionResponse, ModelError> {
        let tool_calls = request
            .tools
            .first()
            .map(|t| {
                vec![ToolCall {
                    id: format!("call_ollama_{}", Ulid::new()),
                    name: t.name.clone(),
                    arguments_json: r#"{"status":"processed"}"#.to_string(),
                }]
            })
            .unwrap_or_default();

        let prompt_tokens = request.messages.iter().map(|m| m.content.len() / 4).sum();
        let completion_tokens = 20;

        Ok(CompletionResponse {
            id: format!("ollama-{}", Ulid::new()),
            content: "Response generated by local Ollama adaptor".to_string(),
            tool_calls,
            usage: TokenUsage {
                prompt_tokens,
                completion_tokens,
                total_tokens: prompt_tokens + completion_tokens,
                estimated_cost_usd: 0.0, // Free local model execution
            },
            provider_name: self.name().to_string(),
        })
    }
}
